[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = false
optimizer = true
optimizer_runs = 200

[profile.env]
PRIVATE_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
